### ISSUE TITLE
Define Interface

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/safeposix-rust#1]
I've set up an interface directory where we can mirror the [interface we had in Repy](https://github.com/Lind-Project/nacl_repy/tree/master/repy).

This includes:

- file operations
- networking
- time related operations
- misc (locks etc)

Let's find equivalents in rust for these functions and wrap them to expose for use in safeposix-rust.

**Comment by rennergade** [comment]
File, Time and, Misc are done for now, but may need some slight tweaks. I'll also be adding a new interface "pipe" for pipes shortly. Networking will be tackled in a few weeks.

@JustinCappos we talked about adapating this from Repy a few times at the meeting, and your concern that we were adapting things that we don't really need to. 

Time and Misc both just generally expose things that we need without adding much overhead, but File does some of the stuff repy does with Files (keeping an open file list, write/readat, etc). I'd love to have your opinion on if these things are worthwhile.

[Here's a link to the File interface](https://github.com/Lind-Project/safeposix-rust/blob/main/src/interface/file.rs). Can you give me any thoughts?

**Comment by JustinCappos** [comment]
You don't need readat / writeat, etc. unless it simplifies your code for
some reason.  You should decide what interface makes sense for you.
