### ISSUE TITLE
Port FS System Calls

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/safeposix-rust#10]
The major transition here will be porting the system calls from Repy SafePOSIX to Rust SafePOSIX.

We should re-implement the system calls found [here](https://github.com/Lind-Project/nacl_repy/blob/master/seattlelib/lind_fs_calls.py) in the old repo to [here](https://github.com/Lind-Project/safeposix-rust/blob/main/src/safeposix/syscalls/fs_calls.rs) in the new one.

We'll also need to port the corresponding constants files.

**Comment by rennergade** [comment]
To do this, we shouldn't use any rust libraries (i.e. you should never have to add a `use ...` line, instead make use of the functions we've exported with the `interface::` crate.

**Comment by TristanB22** [comment]
FILESYSTEM
: load 
: load special files
: blank init

METADATA
: restore
: remove
: persist

REBUILD INODE SYSTEM

FS CALLS
: exit
Tristan : fstat
Tristan : stat
: fstatfs
: statfs
Tristan : access
: chdir
: mkdir
: rmdir
: link
: unlink
: open 
: creat
: lseek
: read
: pread
: write
: pwrite
: close
: dup
: dup2
: fcntl
: getdents
: chmod
: truncate 
: ftruncate
: mknod
: getuid
: geteuid
: getgid
: getegid
: getpid
: getppid
: getrlimit
: setrlimit
: flock
: remake
: pipe
: pipe2
: fork
: exec
: mmap
: munmap

CHR FILE HELPERS
: read chr file
: write chr file
: istat helper

**Comment by rennergade** [comment]
This should be done once pipe and getdents are merged. Great job everyone.

**Comment by kliu513** [comment]
I think it's time to close this issue?

**Comment by rennergade** [comment]
Yep. Great job everyone!
