### ISSUE TITLE
Port SYS System Calls

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/safeposix-rust#11]
This is the same [as this issue](https://github.com/Lind-Project/safeposix-rust/issues/10), but for the SYS calls. These were originally in the FS file for repy safeposix, but we want in a separate file now.

- getpid
- getppid
- getgid
- getuid
- getegid
- geteuid
- getrlimit
- setrlimit
- exit
- fork
- exec

**Comment by rennergade** [comment]
@jesings said he'll put in exit, fork, and exec.

@TristanB22 the rest of these should be the simplest ones, so might be a good starting point!

**Comment by rennergade** [comment]
Are these all "completed" I think the answer is yes

**Comment by TristanB22** [comment]
Yes, I believe that they are. Jonathan looked over the ones I wrote and made edits. Just needs your signoff.

On Jun 23, 2021, at 8:54 PM, Nicholas Renner ***@***.***> wrote:

﻿

Are these all "completed" I think the answer is yes
