### ISSUE TITLE
Translate Tests

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/safeposix-rust#12]
We want to translate the tests from repy SafePOSIX to here. [This test directory](https://github.com/Lind-Project/nacl_repy/tree/master/seattlelib/tests) has the tests we want to translate.

There's probably more than we need here, at this point we should probably just translate the unit tests that being with "ut_lind_"

**Comment by TristanB22** [comment]
ut_lind_fs_broken_close.py
ut_lind_fs_chmod.py
ut_lind_fs_dir_chdir.py
ut_lind_fs_dir_mode.py
ut_lind_fs_dir_multiple.py
ut_lind_fs_dup.py
ut_lind_fs_dup2.py
ut_lind_fs_fcntl.py
ut_lind_fs_fdflags.py
ut_lind_fs_file_link_unlink.py
ut_lind_fs_file_lseek_past_end.py
ut_lind_fs_file_read_write.py
ut_lind_fs_fstat_complex.py
ut_lind_fs_getdents.py
ut_lind_fs_getuid.py
ut_lind_fs_load_fs.py
ut_lind_fs_mknod.py
ut_lind_fs_multiple_open.py
ut_lind_fs_persistance_setup.py
ut_lind_fs_persistance_test.py
ut_lind_fs_rmdir.py
ut_lind_fs_simple.py
ut_lind_fs_stat_file_complex.py
ut_lind_fs_stat_file_mode.py
ut_lind_fs_statfs.py
ut_lind_fs_truncate.py
ut_lind_net_bind.py
ut_lind_net_bind_multiple.py
ut_lind_net_bind_on_zero.py
ut_lind_net_connect_basic_udp.py
ut_lind_net_getpeername.py
ut_lind_net_getsockname.py
ut_lind_net_listen.py
ut_lind_net_poll.py
ut_lind_net_recvfrom.py
ut_lind_net_select.py
ut_lind_net_shutdown.py
ut_lind_net_socket.py
ut_lind_net_socketoptions.py
ut_lind_net_socketpair.py
ut_lind_net_udp_bad_bind.py
ut_lind_net_udp_connect.py
ut_lind_net_udp_simple.py
ut_seattlelibtests_teststruct.mix

**Comment by rennergade** [comment]
Now that we've completed most of the calls lets make sure all of these are translated, and try to add more corner cases.

**Comment by TristanB22** [comment]
All of the file system tests are done! Will work on net tests and then add some more corner cases.

**Comment by kliu513** [comment]
Let's try to mark our names here before we work on each test so that we don't do repetitive work! @TristanB22

**Comment by TristanB22** [comment]
Ok @kliu513 ! The branch that I am working on right now is net_tests. Not totally working yet, though! I also had to comment out the fs tests because they weren't allowing the net tests to run properly. I imagine that it is a concurrence issue.

**Comment by rennergade** [comment]
@TristanB22 something I'd like to see soon is if we could make the tests such that we don't have to delete the entire filesystem every time we test it. Can you work on that?

**Comment by TristanB22** [comment]
@rennergade yes, I can try to get that done for you. Do you mean like removing all of the metadata files in between “cargo test”s or lindrustinit() and lindrustfinalize()’s?

**Comment by rennergade** [comment]
@TristanB22 @kliu513 how close are we to having these finished. I think this is the last step before we merge networking and have RustPosix "finished".

**Comment by TristanB22** [comment]
Not yet, I am having issues with the server that I am trying to fix. Almost done.

**Comment by rennergade** [comment]
Done with networking merge!
