### ISSUE TITLE
Reminder

### ISSUE THREAD

**Issue by TristanB22** [Lind-Project/safeposix-rust#36]
Remember to fix the fs_close_syscall when the pipes and sockets are implemented. Currently, some of the functionality is not there for it.

**Comment by TristanB22** [comment]
Remember to uncomment the rmdir test when Kaitlyn's PR is merged

**Comment by rennergade** [comment]
@TristanB22 did this ever get done? Let's not use issues for reminders in the future.

**Comment by TristanB22** [comment]
We didn't get to fix the close_syscall yet, I believe. Sorry about that!
