### ISSUE TITLE
Port Net Calls

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/safeposix-rust#54]
Port the network calls from SafePOSIX to RustPOSIX

**Comment by TristanB22** [comment]
### Calls to do:
socketpair:
getpeername:
getsockname:
gethostname:
getsockopt: Tristan (in progress)
setsockopt: Tristan (in progress)
getifaddrs (we have no idea how to do this one so far):
poll:
epoll_create:
epoll_ctl:
epoll_wait:

**Comment by TristanB22** [comment]
Once the two PR's that I have open are merged, this should be ready for a close.
